### ISSUE TITLE
AttributeError: module 'louvain' has no attribute 'set_rng_seed'

### ISSUE THREAD

**Issue by lu77777777** [theislab/single-cell-tutorial#61]
Hi, Thanks for this detailed tutorial,

When I  run this program, it will stop in the 2.2 normalization section 

the detailed information is: 

computing neighbors
    using 'X_pca' with n_pcs = 15
    finished: added to `.uns['neighbors']`
    'distances', distances for each pair of neighbors
    'connectivities', weighted adjacency matrix (0:00:12)
running Louvain clustering
    using the "louvain" package of Traag (2017)
Traceback (most recent call last):
  File "/data/lu/projects/test/main.py", line 187, in <module>
    sc.tl.louvain(adata_pp, key_added='groups', resolution=0.5)
  File "/data/lu/anaconda3/envs/renv/lib/python3.8/site-packages/scanpy/tools/_louvain.py", line 138, in louvain
    louvain.set_rng_seed(random_state)
AttributeError: module 'louvain' has no attribute 'set_rng_seed'

**Comment by lu77777777** [comment]
solved

https://github.com/theislab/scanpy/issues/1191
